In [37]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [38]:
np.random.seed(42)

In [39]:
train = pd.read_csv('/home/tezaa/Documents/Documents/Data Mining/Kaggle/Leaf/train.csv')

In [40]:
x_train = train.drop(['id','species'],axis = 1).values

In [41]:
le = LabelEncoder().fit(train['species'])

In [42]:
y_train = le.transform(train['species'])

In [43]:
scaler = StandardScaler().fit(x_train)

In [44]:
x_train = scaler.transform(x_train)

In [77]:
params = {'C':[100,1000],'tol':[0.01,0.00001]}

In [68]:
log_reg = LogisticRegression(solver = 'lbfgs',multi_class = 'multinomial')

In [78]:
clf = GridSearchCV(log_reg,params,scoring = 'log_loss', refit = "True", n_jobs = -1 , cv = 5)

In [79]:
clf.fit(x_train,y_train)

/home/tezaa/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/home/tezaa/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/home/tezaa/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = o

GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'C': [100, 5000], 'tol': [0.01, 1e-05]},
       pre_dispatch='2*n_jobs', refit='True', scoring='log_loss',
       verbose=0)

In [80]:
print ("best params: " + str(clf.best_params_))

best params: {'C': 5000, 'tol': 1e-05}


In [63]:
for params,mean_score, scores in clf.grid_scores_:
    print ("%0.3f (+/-%0.03f) for %r" % (mean_score, scores.std(), params))
    print (scores)

-0.052 (+/-0.033) for {'C': 500, 'tol': 0.01}
[-0.07194116 -0.01869673 -0.10669679 -0.03548736 -0.02707999]
-0.042 (+/-0.023) for {'C': 500, 'tol': 0.0001}
[-0.04492464 -0.02019783 -0.08122239 -0.04323846 -0.01881017]
-0.063 (+/-0.040) for {'C': 5000, 'tol': 0.01}
[-0.08934028 -0.01981096 -0.12796784 -0.04677589 -0.0299348 ]
-0.042 (+/-0.027) for {'C': 5000, 'tol': 0.0001}
[-0.04544954 -0.01309867 -0.08871605 -0.04416828 -0.01835949]


In [72]:
test = pd.read_csv('/home/tezaa/Documents/Documents/Data Mining/Kaggle/Leaf/test.csv')

In [52]:
test_ids = test.pop('id')


In [53]:
x_test = test.values

In [54]:
x_test = scaler.transform(x_test)

In [81]:
y_test = clf.predict_proba(x_test)

In [82]:
submission = pd.DataFrame(y_test, index = test_ids,columns = le.classes_)

In [83]:
submission.to_csv('submission3.csv')